name: tugas2_tpm_033_144
description: "Flutter app dengan fitur autentikasi REST API, kalkulator, dan utility tools."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
